### ISSUE TITLE
Add possibility to cancel iZettle payment.

### ISSUE THREAD

**Issue by ViddeM** [hulthe/strecklistan#63] opened 2021-06-03 16:43 UTC
Add a button to cancel an ongoing izettle payment to the frontend (when the frontend is in izettle poll mode) which should cancel the current izettle payment. Undefined behaviour when a payment is paid and cancelled at the same time, could be problematic to implement.

**Comment by hulthe** [comment] 2021-06-03 23:15
Paying a payment should override the cancellation, which should work just fine :+1:

**Comment by hulthe** [comment] 2021-06-03 23:16
Also this is a duplicate of #60 x)

**Closed as completed by hulthe** 2021-06-03 23:16 UTC
Labels: backend, frontend/ui
